config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :wikis do
       resources :collaborators, only: [:new, :create, :destroy]
  end
  resources :charges, only: [:new, :create]

  post 'downgrade_account' => 'users#downgrade_account'
  get 'about' => 'welcome#about'
  root 'welcome#index'

end

app/models/amount.rb
class Amount < ApplicationRecord 

#PRIVATE
 private

   def self.premium
     15_00
   end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord

  belongs_to :wiki
  belongs_to :user

  validates :user, uniqueness: { scope: :wiki }
  validate :user_is_not_owner
 

  private

  def user_is_not_owner
    return unless user == wiki.user
    errors.add(:user, "You are the owner of the page")
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
 
  has_many :collaborators
  has_many :wikis, dependent: :destroy, through: :collaborators

  after_initialize :default_user_role

  enum role: [:member, :premium, :admin]


#DEFAULT USER ROLE
  def default_user_role
    self.role ||= :member
  end

end

app/models/wiki.rb
class Wiki < ApplicationRecord

  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :user, presence: true
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:index, :about, :show]

  include Pundit
  protect_from_forgery

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

#NEW
  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Blocipedia Premium Account",     
      amount: Amount.premium
    }
  end

#CREATE
  def create
    # Creates a Stripe Customer object, for associating with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
 
    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: Amount.premium,
      description: "Blocipedia Premium Account - #{current_user.email}",
      currency: 'usd'
    )
     
    flash[:notice] = "Thank you for your payment, #{current_user.email}! Your account is now upgraded."
    current_user.premium!
    redirect_to :root
 
    # Stripe will send back CardErrors, with friendly messages when something goes wrong.
    # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

#NEW
   def new
     @collaborator = Collaborator.new
   end

#CREATE
   def create
     @wiki = Wiki.find(params[:wiki_id])
     @user = User.find_by_email(params[:collaborator])

     if @user
        @collaborator = Collaborator.new(wiki_id: @wiki.id, user_id: @user.id)
        if @collaborator.save
            flash[:notice] = "#{@user.email} was added as a collaborator."
            redirect_to edit_wiki_path(@wiki)
        else
            flash[:alert] = "There was an error adding this collaborator. Please try again."
            redirect_to edit_wiki_path(@wiki)
        end
      else
        flash[:alert] = "User not found"
        redirect_to edit_wiki_path(@wiki)
      end   
    end

#DESTROY
  def destroy
     @wiki = Wiki.find(params[:wiki_id])
     @collaborator = Collaborator.find(params[:id])
     @collaborator_user = User.find(@collaborator.user_id)

     if @collaborator.destroy
       flash[:notice] = "#{@collaborator_user.email} was removed as a collaborator."
       redirect_to edit_wiki_path(@wiki)
     else
       flash[:alert] = "There was an error removing this collaborator. Please try again."
       redirect_to edit_wiki_path(@wiki)
     end    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def downgrade_account
      current_user.member!
    
      flash[:notice] = "Your account has now been downgraded."
      redirect_to edit_user_registration_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

#INDEX
  def index
    @wikis = policy_scope(Wiki)
  end

#SHOW
  def show
    @wiki = Wiki.find(params[:id])
  end

#NEW
  def new
    @wiki = Wiki.new
    authorize @wiki
  end

#CREATE
  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

#EDIT
  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

#UPDATE
  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :edit
    end 
  end

#DESTROY
  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
   def form_group_tag(errors, &block)
     css_class = 'form-group'
     css_class << ' has-error' if errors.any?

     content_tag :div, capture(&block), class: css_class
   end

#MARKDOWN
   def markdown(text)
       @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, {
          autolink: true,
          space_after_headers: true,
          fenced_code_blocks: true,
          underline: true,
          highlight: true,
          footnotes: true,
          tables: true
          })
       @markdown.render(text).html_safe
   end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
   def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
    count: resource.errors.count,
    resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-block"> <button type="button" class="close" data-dismiss="alert">x</button>
        <h4>#{sentence}</h4>
        #{messages}
       </div>
       HTML

       html.html_safe
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/collaborators/_collaborators.html.erb
<b>Collaborators</b>
<br>   

  <ul class="list-group">
    <% wiki.collaborators.each do |c| %>
       <% user = User.find(c.user_id) %>
         <li class="list-group-item">
         <%= link_to "X", wiki_collaborator_path(@wiki, c), class: 'btn btn-danger btn-sm', method: :delete %> 
         <%=user.email %>
         </li>
    <% end %>
  </ul>

  <br>

  <%= form_for [@wiki, Collaborator.new] do |f| %>
      <%= email_field_tag :collaborator %>
      <br><br>
      <%= f.submit "Add collaborator", class: 'btn' %>
  <% end %>
 
 <br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 </head>

  <body>
  <div class="container">
    <ul class="nav nav-tabs" >
     <li><%= link_to "Blocipedia", root_path %></li>
     <li><%= link_to "Wikis", wikis_path %></li>
     <li><%= link_to "About", about_path %></li>

    <% if user_signed_in? %>
     <div>
       <li class="pull-right">Signed in as: <strong><%= current_user.email %></strong>
           <% if current_user.role == "premium" %><i> (Premium)</i><% end %></li><br>
       <li class="pull-right"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
       <div><li class="pull-right">|</li></div>
       <li class="pull-right"><%= link_to "Edit profile", edit_user_registration_path %></li>
     </div>
    <% else %>
       <li class="pull-right"><%= link_to "Sign Up", new_user_registration_path %></li>
       <li class="pull-right"><%= link_to "Sign In", new_user_session_path %></li>
    <% end %>
   </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

   <%= yield %>
  </div>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
   <h1>Blocipedia: Social, Markdown Wikis</h1>
   <h2>Create and share Markdown Wikis</h2>
</div>
	
<% unless user_signed_in? %>
 <div class="row">
   <div class="col-md-4">
     <h2>Free Account</h2>
     <p>Create as many public wikis as you want!</p>
   </div>
   <div class="col-md-4">
     <h2>Premium Account</h2>
     <p>Create private wikis!</p>
   </div>
</div>
<% end %>

app/views/wikis/_form.html.erb
 <%= form_for @wiki do |f| %>
    <div class="form-group">
       <%= f.label :title %>
       <%= f.text_field :title, class: 'form-control', placeholder: "Enter title" %>
     </div>

     <div class="form-group">
       <%= f.label :body %>
       <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki content" %>
     </div>
 
    <% if current_user.admin? || (current_user.premium? && @wiki.user == current_user) %>
      <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
          <%= f.check_box :private %> Private wiki
        <% end %>
      </div>
    <% end %>      
     
    <%= f.submit "Save", class: 'btn btn-success' %>
 <% end %>

app/views/wikis/edit.html.erb
 <h1>Edit Wiki</h1>

 <div class="row">

   <div class="col-md-4">
     <b>Guidelines:</b>
     <ul>
       <li>1</li>
       <li>2</li>
       <li>3</li>
     </ul>
     
     <br>

     <% if current_user.admin? || (@wiki.user == current_user && current_user.premium?) %>  
       <%= render partial: "collaborators/collaborators", locals: { wiki: @wiki } %>
     <% end %>
   </div>


   <div class="col-md-8">
     <%= render partial: "form", locals: { wiki: @wiki } %>
   </div>

 </div>

app/views/wikis/index.html.erb
 <h1>Index of Wiki Pages</h1>
 
<br>
 <div class="row">
   <div class="col-md-8">
      <% @wikis.each do |wiki| %>

       <% if wiki.private && wiki.user == current_user && current_user.member? %>
          <% wiki.private = 'false' %>
       <% end %>         

        <div class="media">
          <div class="media-body">
           <h4 class="media-heading">
             <%= link_to wiki.title, wiki %>
           </h4>
            <small>
              <% if wiki.private %><i>(Private)</i><% end %>
              updated <%= time_ago_in_words(wiki.updated_at) %> ago
            </small>    
          </div>
        </div>
     <% end %>
   </div>

 <% if user_signed_in? %>
   <div class="col-md-4">
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
   </div>
 <% end %>
</div>

app/views/wikis/new.html.erb
 <h1>New Wiki</h1>

 <div class="row">

  <div class="col-md-4">
   <b>Guidelines:</b>
     <ul>
       <li>1</li>
       <li>2</li>
       <li>3</li>
     </ul>
  
   <br>

   <% if current_user.admin? || current_user.premium? %>
     <%= render partial: "collaborators", locals: { wiki: @wiki, user: @user } %>
   <% end %>

   </div>

  <div class="col-md-8">
    <%= render partial: "form", locals: { wiki: @wiki } %> 
  </div>

 </div>

app/views/wikis/show.html.erb
<div>
   <h1>
     <%= @wiki.title %> <br>
   </h1>
   <small>
     updated <%= time_ago_in_words(@wiki.updated_at) %> ago
   </small>
 </div>
 <br>
 <div class="row">
   <div class="col-md-8">
     <p><%= markdown(@wiki.body) %></p>
   </div>

    <div class="col-md-4">
      <% if user_signed_in? %>
        <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
      <% end %>
      <% if policy(@wiki).destroy? %>
        <%= link_to "Delete Wiki", [@wiki], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki page?' } %>
      <% end %>
    </div>
 </div>